name: MorphX
version: 1.0.0
authors:
  - roci33
api: 3.0.0
main: Roci33\MorphX\Main
permissions:
  morphx.command.morph:
    default: op
    description: "Allows to use every morphx command"
