name: MorphX
version: 0.1.0
authors:
  - roci33
api: 3.0.0
main: Roci33\MorphX\Main
permissions:
  morphx.command:
    default: op
    description: "Allows to use every morphx features"
    children:
         morphx.command.morph:
            default: op
            description: "Allows the player to be a mob"
